[project]
name = "s6e9-ev-purchases"
version = "0.1.0"
description = "Kaggle Playground S6E9: Predicting EV Purchases (ROC-AUC)"
readme = "README.md"
authors = [
    { name = "lionel509", email = "lionelweng@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "catboost>=1.2.10",
    "kaggle>=2.2",
    "lightgbm>=4.7.0",
    "numba>=0.67.0",
    "numpy>=2.5.2",
    "optuna>=4.9.0",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pytabkit>=1.7.3",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.1",
    "tabm>=0.0.3",
    "tiktoken>=0.14.0",
    "torch>=2.14.0",
    "xgboost>=3.4.1",
]

[project.scripts]
s6e9-ev-purchases = "s6e9_ev_purchases:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
